name: Generate NCI resources report
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run  
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.SSH_KEY}}
          command_timeout: 60m
          script: |
              module use /g/data3/xp65/public/modules
              module load conda/analysis3
              which python > python.txt
              date > date.txt
      
